config/routes.rb
Artiste::Application.routes.draw do
  devise_for :users do
    get "logout" => "devise/sessions#destroy"
  end

  root to: "home#index"

  namespace :admin do
    root to: "dashboard#index"

    resources :categories do
      post :sort, on: :collection
    end
    resources :works do
      post :sort, on: :collection
    end
    resources :pages do
      post :sort, on: :collection
    end
    resources :events do
      post :sort, on: :collection
    end
    resources :inquiries do
      post :archive, on: :member
      post :unarchive, on: :member
    end
    resources :users
    resources :settings, only: [:index, :edit, :update]
  end

  resources :works, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :pages, only: [:show]
  resources :inquiries, only: [:new, :create]

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base

  attr_accessible :full_name, :email, :phone, :address, :message, :archived

  validates :full_name, presence: true
  validates :email, presence: true
  validates :message, presence: true

  scope :archive, -> { where(archived: true) }
  scope :inbox, -> { where(archived: false) }

end

app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < Admin::AdminController

  def index
    @inbox = Inquiry.inbox.all
    @archive = Inquiry.archive.all
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  def destroy
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.destroy
      redirect_to admin_inquiries_path, notice: "Inquiry deleted!"
    else
      redirect_to admin_inquiries_path, alert: "Could not delete"
    end
  end

  def archive
    @inquiry = Inquiry.find(params[:id])
    @inquiry.update_attribute(:archived, true)
    respond_to :js
  end

  def unarchive
    @inquiry = Inquiry.find(params[:id])
    @inquiry.update_attribute(:archived, false)
    respond_to :js
  end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
end

app/views/admin/inquiries/_item.html.haml
%tr{id: "inquiry_#{inquiry.id}"}
  %td= abbr_date_time inquiry.created_at
  %td= inquiry.full_name
  %td= inquiry.email
  %td= page_excerpt inquiry.message
  %td
    = link_to "View", admin_inquiry_path(inquiry), class: "btn btn-success"
    - if inquiry.archived
      = link_to "Unarchive", unarchive_admin_inquiry_path(inquiry), remote: true, method: :post, class: "archive-control unarchive btn btn-info"
    - else
      = link_to "Archive", archive_admin_inquiry_path(inquiry), remote: true, method: :post, class: "archive-control archive btn btn-info"
    = link_to "Delete", admin_inquiry_path(inquiry), method: :delete, class: "btn btn-danger"

app/views/admin/inquiries/archive.js.erb
$('#inquiry_' + <%= @inquiry.id %>).remove()
$('#archive tr.nothing-yet').remove()
$('#archive tbody').append('<%= j render partial: "admin/inquiries/item", locals: {inquiry: @inquiry} %>')

app/views/admin/inquiries/index.html.haml
.container
  .row-fluid
    .col-lg-12
      %h2 Inquiries

.container
  %ul.nav.nav-tabs
    %li
      %a{href: "#inbox", data: {toggle: "tab"}} Inbox
    %li
      %a{href: "#archive", data: {toggle: "tab"}} Archive
    
  .tab-content

    #inbox.tab-pane
      .row-fluid
        .col-lg-12
          %table.table.table-bordered.table-condensed
            %thead
              %tr
                %th Created At
                %th Full Name
                %th Email
                %th Message
                %th.table-inquiry-actions Actions
            %tbody
              - if @inbox.present?
                - @inbox.each do |inquiry|
                  = render partial: "admin/inquiries/item", locals: {inquiry: inquiry}

              - else
                %tr.nothing-yet
                  %td{colspan: 5} You haven't received any new inquiries.

    #archive.tab-pane
      .row-fluid
        .col-lg-12
          %table.table.table-bordered.table-condensed
            %thead
              %tr
                %th Created At
                %th Full Name
                %th Email
                %th Message
                %th.table-inquiry-actions Actions
            %tbody
              - if @archive.present?
                - @archive.each do |inquiry|
                  = render partial: "admin/inquiries/item", locals: {inquiry: inquiry}

              - else
                %tr.nothing-yet
                  %td{colspan: 5} You haven't archived any inquiries.

:coffeescript
  $(document).ready ->
    $('a[href="#inbox"]').tab('show')

app/views/admin/inquiries/show.html.haml
%h2 View Inquiry

%table.table.table-bordered.table-condensed
  %tbody
    %tr
      %td
        %strong Created At
      %td= pretty_date_time @inquiry.created_at
    %tr
      %td 
        %strong Name
      %td= @inquiry.full_name
    %tr
      %td 
        %strong Email Address
      %td= @inquiry.email
    %tr
      %td
        %strong Phone Number
      %td= @inquiry.phone rescue "Not provided"
    %tr
      %td
        %strong Address
      %td= @inquiry.address rescue "Not provided"
    %tr
      %td
        %strong Message
      %td= @inquiry.message 

app/views/admin/inquiries/unarchive.js.erb
$('#inquiry_' + <%= @inquiry.id %>).remove()
$('#inbox tr.nothing-yet').remove()
$('#inbox tbody').append('<%= j render partial: "admin/inquiries/item", locals: {inquiry: @inquiry} %>')