config/routes.rb
Artiste::Application.routes.draw do
  devise_for :users do
    get "logout" => "devise/sessions#destroy"
  end

  root to: "home#index"

  namespace :admin do
    root to: "dashboard#index"

    resources :categories do
      post :sort, on: :collection
    end
    resources :works do
      post :sort, on: :collection
    end
    resources :pages do
      post :sort, on: :collection
    end
    resources :events do
      post :sort, on: :collection
    end
    resources :inquiries do
      post :archive, on: :member
      post :unarchive, on: :member
    end
    resources :users
    resources :settings, only: [:index, :edit, :update]
  end

  resources :works, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :pages, only: [:show]
  resources :inquiries, only: [:new, :create]

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  attr_accessible :title, :description, :image, :image_cache, :featured
  mount_uploader :image, ImageUploader

  has_many :works, order: "sort_order asc"

  validates :title, presence: true, uniqueness: true
  before_save :feature

  scope :sorted, -> { order("sort_order asc") }
  scope :featured, -> { where(featured: true) }

  def feature
    if self.featured == true
      Category.update_all({featured: false}, {featured: true})
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  attr_accessible :title, :description, :image, :event_at, :image_cache
  mount_uploader :image, ImageUploader

  validates :title, presence: true

  scope :upcoming, -> { where('event_at >= ?', Time.now.to_s(:db)) }
  scope :previous, -> { where('event_at < ?', Time.now.to_s(:db)) }
  scope :sorted, -> { order("sort_order asc") }

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base

  attr_accessible :full_name, :email, :phone, :address, :message, :archived

  validates :full_name, presence: true
  validates :email, presence: true
  validates :message, presence: true

  scope :archive, -> { where(archived: true) }
  scope :inbox, -> { where(archived: false) }

end

app/models/page.rb
class Page < ActiveRecord::Base
  
  attr_accessible :title, :body, :show_in_nav, :image, :image_cache
  mount_uploader :image, ImageUploader

  validates :title, presence: true, uniqueness: true

  scope :nav, -> { where(show_in_nav: true) }
  scope :sorted, -> { order("sort_order asc") }

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  
  attr_accessible :title, :content

  validates :title, presence: true, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/work.rb
class Work < ActiveRecord::Base
  
  attr_accessible :title, :caption, :produced_at, :image, :featured, :public, :category_id, :image_cache
  mount_uploader :image, ImageUploader

  belongs_to :category

  validates :title, presence: true
  before_save :feature
  
  scope :sorted, -> { order("sort_order asc") }
  scope :featured, -> { where(featured: true) }
  scope :public, -> { where(public: true) }
  scope :uncategorized, -> { where(category_id: nil) }

  def feature
    if self.featured == true
      Work.update_all({:featured => false}, {:featured => true})
    end
  end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base

  layout 'admin'
  before_filter :authenticate_user!
  
  def index
  end

  private

    def crud_success klass=nil, verb=""
      unless klass.nil?
        redirect_to controller: "admin/#{klass.downcase.pluralize}", action: "index"
        flash[:notice] = "#{klass.titleize} #{verb}!"
      end
    end

    def crud_failure klass=nil, action="", verb="", obj=nil
      unless klass.nil?
        if obj.nil?
          redirect_to controller: "admin/#{klass.downcase.pluralize}", action: action
        else
          redirect_to controller: "admin/#{klass.downcase.pluralize}", action: "edit", id: obj.id
        end
        flash[:alert] = "#{klass.titleize} could not be #{verb}. Please try again."
      end
    end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::AdminController

  before_filter :find_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.sorted.all
  end

  def show
    render action: 'edit'
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      crud_success "page", "saved"
    else
      crud_failure "page", "new", "saved"
    end
  end

  def edit
  end

  def update
    if @page.update_attributes(params[:page])
      crud_success "page", "updated"
    else
      crud_failure "page", "edit", "updated", @page
    end
  end

  def destroy
    if @page.destroy
      crud_success "page", "deleted"
    else
      crud_failure "page", "index", "deleted"
    end
  end

  def sort
    params[:page].each_with_index do |id, index|
      Page.update_all({sort_order: index+1}, {id: id})
    end
    render nothing: true
  end

  private

    def find_page
      @page = Page.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
end

app/helpers/admin/navigation_helper.rb
module Admin::NavigationHelper

  def active_for_controller kontroller
    return "active" if controller.controller_name == kontroller
  end

end

app/helpers/admin/tables_helper.rb
module Admin::TablesHelper

  def page_excerpt body=nil, length=150
    unless body.nil?
      safe = strip_tags(body)
      trunc = truncate(safe, length: length)
    end
  end

  def pretty_date datestamp
    unless datestamp.nil?
      date = datestamp.strftime('%B %d, %Y')
    end
  end

  def pretty_date_time timestamp
    unless timestamp.nil?
      datetime = timestamp.in_time_zone('America/Chicago').strftime('%B %d, %Y at %l:%M %p')
    end
  end

  def abbr_date_time timestamp
    unless timestamp.nil?
      datetime = timestamp.in_time_zone('America/Chicago').strftime('%m/%d/%Y %l:%M %p')
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/pages/_form.html.haml
= simple_form_for([:admin, @page], :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' }}) do |f|
  = f.input :title, required: true
  = f.input :show_in_nav, as: :select
  = f.input :body
  = image_tag @page.image.small if @page.image?
  = f.input :image, label: "Upload Image"
  = f.input :image_cache, as: :hidden
  = f.button :submit, label: "Add Page", class: "btn btn-success"
  .preloader= image_tag "preloader.gif"

app/views/admin/pages/_table.html.haml
%table.table.table-bordered.table-condensed
  %thead
    %tr
      %th.table-sort Sort
      %th Title
      %th Excerpt
      %th.table-image Image Preview
      %th.table-actions Actions
  %tbody.sortable-table{:'data-update-url' => sort_admin_pages_url}
    -if @pages.present?
      - @pages.each do |page|
        %tr{id: "page_#{page.id}"}
          %td
            .sort-handle
              %i.glyphicon.glyphicon-sort
          %td= page.title
          %td= page_excerpt page.body
          %td= image_tag page.image.thumb if page.image.present?
          %td
            = link_to "Edit", edit_admin_page_path(page), class: "btn btn-info"
            = link_to "Delete", admin_page_path(page), method: :delete, class: "btn btn-danger"

    - else
      %tr
        %td{colspan: 5} You haven't added any pages yet.

app/views/admin/pages/edit.html.haml
%h2 Edit Page

= render "admin/pages/form"

app/views/admin/pages/index.html.haml
.container
  .row-fluid
    .col-lg-9
      %h2 Pages
    .col-lg-3
      = link_to "Add Page", new_admin_page_path, class: "btn btn-primary pull-right"

.container
  .row-fluid
    .col-lg-12.col-tables
      = render "admin/pages/table"

app/views/admin/pages/new.html.haml
%h2 Add A New Page

= render "admin/pages/form"

app/views/layouts/admin/_flash.html.haml
- if flash.present?
  .container
    .row-fluid
      .col-lg-12
        - flash.each do |name, msg|
          - if name.to_s == "notice"
            %p.alert.alert-success
              %a.close.close-element &times;
              = msg
          - elsif name.to_s == "alert"
            %p.alert.alert-danger
              %a.close.close-element &times;
              = msg
          - else
            %p.alert.alert-info
              %a.close.close-element &times;
              = msg