config/routes.rb
Artiste::Application.routes.draw do
  devise_for :users do
    get "logout" => "devise/sessions#destroy"
  end

  root to: "home#index"

  namespace :admin do
    root to: "dashboard#index"

    resources :categories do
      post :sort, on: :collection
    end
    resources :works do
      post :sort, on: :collection
    end
    resources :pages do
      post :sort, on: :collection
    end
    resources :events do
      post :sort, on: :collection
    end
    resources :inquiries do
      post :archive, on: :member
      post :unarchive, on: :member
    end
    resources :users
    resources :settings, only: [:index, :edit, :update]
  end

  resources :works, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :pages, only: [:show]
  resources :inquiries, only: [:new, :create]

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  attr_accessible :title, :description, :image, :event_at, :image_cache
  mount_uploader :image, ImageUploader

  validates :title, presence: true

  scope :upcoming, -> { where('event_at >= ?', Time.now.to_s(:db)) }
  scope :previous, -> { where('event_at < ?', Time.now.to_s(:db)) }
  scope :sorted, -> { order("sort_order asc") }

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController

  before_filter :find_event, only: [:show, :edit, :destroy]

  def index
    @events = Event.sorted.all
    @upcoming_events = Event.sorted.upcoming
    @previous_events = Event.sorted.previous
  end

  def show
    render action: 'edit'
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    @event.event_at = @event.event_at + 5.hours
    if @event.save
      crud_success "event", "saved"
    else
      crud_failure "event", "new", "saved"
    
    end
  end

  def edit
  end

  def update
    @event = Event.find(params[:id])
    @event.event_at = @event.event_at + 5.hours
    if @event.update_attributes(params[:event])
      crud_success "event", "updated"
    else
      crud_failure "event", "edit", "updated", @event
    end
  end

  def destroy
    if @event.destroy
      # crud_success("deleted")
      crud_success "event", "deleted"
    else
      # crud_failure ("deleted", "index")
      crud_failure "event", "index", "deleted"
    end
  end

  def sort
    params[:event].each_with_index do |id, index|
      Event.update_all({sort_order: index+1}, {id: id})
    end
    render nothing: true
  end

  private

    def find_event
      @event = Event.find(params[:id])
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/views/admin/events/_form.html.haml
= simple_form_for([:admin, @event], :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' }}) do |f|
  = f.input :title
  = f.input :event_at, label: "Event Date", as: :string, input_html: {class: "datetimepicker form-control"}
  = f.input :description
  = image_tag @event.image.small.url if @event.image?
  = f.input :image, label: "Upload Image"
  = f.input :image_cache, as: :hidden
  = f.button :submit, label: "Add Event", class: "btn btn-success"

app/views/admin/events/_table.html.haml
- if @upcoming_events.present?
  %h3 Upcoming Events
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th.table-sort Sort
        %th Title
        %th Event Date
        %th Excerpt
        %th.table-image Image Preview
        %th.table-actions Actions
    %tbody.sortable-table{:'data-update-url' => sort_admin_events_url}
      - @upcoming_events.each do |event|
        %tr{id: "event_#{event.id}"}
          %td
            .sort-handle
              %i.glyphicon.glyphicon-sort
          %td= event.title
          %td= pretty_date_time event.event_at
          %td= page_excerpt event.description
          %td= image_tag event.image.thumb if event.image.present?
          %td
            = link_to "Edit", edit_admin_event_path(event), class: "btn btn-info"
            = link_to "Delete", admin_event_path(event), method: :delete, class: "btn btn-danger"


- if @previous_events.present?
  %h3 Previous Events
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th.table-sort Sort
        %th Title
        %th Event Date
        %th Excerpt
        %th.table-image Image Preview
        %th.table-actions Actions
    %tbody.sortable-table{:'data-update-url' => sort_admin_events_url}
      - @previous_events.each do |event|
        %tr
          %td
            .sort-handle
              %i.glyphicon.glyphicon-sort
          %td= event.title
          %td= pretty_date event.event_at
          %td= page_excerpt event.description
          %td= image_tag event.image.thumb if event.image.present?
          %td
            = link_to "Edit", edit_admin_event_path(event), class: "btn btn-info"
            = link_to "Delete", admin_event_path(event), method: :delete, class: "btn btn-danger"


- unless @previous_events.present? || @upcoming_events.present?
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th.table-sort Sort
        %th Title
        %th Event Date
        %th Excerpt
        %th.table-image Image Preview
        %th.table-actions Actions
    %tbody
      %tr
        %td{colspan: 6} You haven't added any events.

app/views/admin/events/edit.html.haml
%h2 Edit Event

= render "admin/events/form"

app/views/admin/events/index.html.haml
.container
  .row-fluid
    .col-lg-9
      %h2 Events
    .col-lg-3
      = link_to "Add Event", new_admin_event_path, class: "btn btn-primary pull-right"

.container
  .row-fluid
    .col-lg-12.col-tables
      = render "admin/events/table"

app/views/admin/events/new.html.haml
%h2 Add New Event

= render "admin/events/form"