config/routes.rb
Artiste::Application.routes.draw do
  devise_for :users do
    get "logout" => "devise/sessions#destroy"
  end

  root to: "home#index"

  namespace :admin do
    root to: "dashboard#index"

    resources :categories do
      post :sort, on: :collection
    end
    resources :works do
      post :sort, on: :collection
    end
    resources :pages do
      post :sort, on: :collection
    end
    resources :events do
      post :sort, on: :collection
    end
    resources :inquiries do
      post :archive, on: :member
      post :unarchive, on: :member
    end
    resources :users
    resources :settings, only: [:index, :edit, :update]
  end

  resources :works, only: [:index, :show]
  resources :events, only: [:index, :show]
  resources :pages, only: [:show]
  resources :inquiries, only: [:new, :create]

end

app/models/work.rb
class Work < ActiveRecord::Base
  
  attr_accessible :title, :caption, :produced_at, :image, :featured, :public, :category_id, :image_cache
  mount_uploader :image, ImageUploader

  belongs_to :category

  validates :title, presence: true
  before_save :feature
  
  scope :sorted, -> { order("sort_order asc") }
  scope :featured, -> { where(featured: true) }
  scope :public, -> { where(public: true) }
  scope :uncategorized, -> { where(category_id: nil) }

  def feature
    if self.featured == true
      Work.update_all({:featured => false}, {:featured => true})
    end
  end

end

app/controllers/admin/works_controller.rb
class Admin::WorksController < Admin::AdminController

  before_filter :find_work, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.sorted.all
    @uncategorized = Work.uncategorized.sorted.all
    @works = Work.sorted.all
  end

  def show
    render action: 'edit'
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(params[:work])
    if @work.save
      crud_success "work", "saved"
    else
      crud_failure "work", "new", "saved"
    end
  end

  def edit
  end

  def update
    if @work.update_attributes(params[:work])
      crud_success "work", "updated"
    else
      crud_failure "work", "edit", "updated", @work
    end
  end

  def destroy
    if @work.destroy
      crud_success "work", "deleted"
    else
      crud_failure "work", "index", "deleted"
    end
  end

  def sort
    params[:work].each_with_index do |id, index|
      Work.update_all({sort_order: index+1}, {id: id})
    end
    render nothing: true
  end

  private

    def find_work
      @work = Work.find(params[:id])
    end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
end

app/views/admin/works/_form.html.haml
= simple_form_for([:admin, @work], :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' }}) do |f|
  = f.input :title, required: true
  = f.input :public, as: :select, required: true
  = f.input :featured, as: :select, required: true
  = f.association :category
  = f.input :caption
  = f.input :produced_at, as: :string, input_html: {class: "datepicker form-control"}
  = image_tag @work.image.small.url if @work.image?
  = f.input :image, label: "Upload Image"
  = f.input :image_cache, as: :hidden
  = f.button :submit, label: "Add Work", class: "btn btn-success"
  .preloader= image_tag "preloader.gif"

app/views/admin/works/_table.html.haml
- if @categories.present?
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th.table-sort Sort
        %th Title
        %th Category
        %th Public
        %th Featured
        %th Caption
        %th.table-image Image Preview
        %th.table-actions Actions
    %tbody.sortable-table{:'data-update-url' => sort_admin_works_url}
      - @categories.each do |category|
        - if category.works.present?
          - category.works.each do |work|
            %tr{id: "work_#{work.id}"}
              %td
                .sort-handle
                  %i.glyphicon.glyphicon-sort
              %td= work.title
              %td= category.title
              %td= work.public ? "Yes" : "No"
              %td= work.featured ? "Yes" : "No"
              %td= work.caption
              %td= image_tag work.image.thumb if work.image.present?
              %td
                = link_to "Edit", edit_admin_work_path(work), class: "btn btn-info"
                = link_to "Delete", admin_work_path(work), method: :delete, class: "btn btn-danger"
      
      - if @uncategorized.present?
        - @uncategorized.each do |work|
          %tr{id: "work_#{work.id}"}
            %td
              .sort-handle
                %i.glyphicon.glyphicon-sort
            %td= work.title
            %td Uncategorized
            %td= work.public ? "Yes" : "No"
            %td= work.featured ? "Yes" : "No"
            %td= work.caption
            %td= image_tag work.image.thumb if work.image.present?
            %td
              = link_to "Edit", edit_admin_work_path(work), class: "btn btn-info"
              = link_to "Delete", admin_work_path(work), method: :delete, class: "btn btn-danger"

- else
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th.table-sort Sort
        %th Title
        %th Public
        %th Featured
        %th Caption
        %th.table-image Image Preview
        %th.table-actions Actions
    %tbody.sortable-table{:'date-update-url' => sort_admin_works_url}
      - @works.each do |work|
        %tr{id: "work_#{work.id}"}
          %td
            .sort-handle
              %i.glyphicon.glyphicon-sort
          %td= work.title
          %td= work.public ? "Yes" : "No"
          %td= work.featured ? "Yes" : "No"
          %td= work.caption
          %td= image_tag work.image.thumb if work.image.present?
          %td
            = link_to "Edit", edit_admin_work_path(work), class: "btn btn-info"
            = link_to "Delete", admin_work_path(work), method: :delete, class: "btn btn-danger"

app/views/admin/works/edit.html.haml
%h2 Edit Work

= render "admin/works/form"

app/views/admin/works/index.html.haml
.container
  .row-fluid
    .col-lg-9
      %h2 Works
    .col-lg-3
      = link_to "Add Work", new_admin_work_path, class: "btn btn-primary pull-right"

.container
  .row-fluid
    .col-lg-12.col-tables
      = render "admin/works/table"

app/views/admin/works/new.html.haml
%h2 Add New Work

= render "admin/works/form"